heroku/buildpacks-ruby

.gitignore
lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/bundle_install.rb
lib/heroku_buildpack_ruby/metadata.rb
lib/heroku_buildpack_ruby/metadata/cnb.rb
lib/heroku_buildpack_ruby/metadata/in_memory.rb
lib/heroku_buildpack_ruby/metadata/v2.rb
lib/heroku_buildpack_ruby/prepare_app_bundler_and_ruby.rb
spec/unit/metadata_spec.rb

This implementation uses the same interface for V2 and CNB. A top level Metadata object is a loose wrapper around a low level metadata store that responds to get/set/fetch. 
I do need to figure out a migration strategy to migrate from existing heroku-buildpack-ruby metadata to this scheme, but that can come later.
As values are set on the metadata stores they're written to disk right away so we don't have to worry about remembering to write to disk when we're done. 
A layer is currently represented as 3 things:
- env
- config
- metadata (store.toml)
Currently, EnvProxy handles writing the env and the config. With the addition of this store, we've got a fairly comprehensive view for a layer. It's a little odd that the EnvProxy knows about config. I might want to change that in the future. …

 Initial Metadata implementation

---

lib/heroku_buildpack_ruby/metadata/in_memory.rb
lib/heroku_buildpack_ruby/metadata/v2.rb
lib/heroku_buildpack_ruby/prepare_app_bundler_and_ruby.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
spec/unit/metadata_spec.rb
spec/unit/ruby_detect_version_spec.rb

When a customer depends on a default ruby version they don't want the app to suddenly break between builds. To help with this we make the version "sticky" by persisting the default version to the metadata store and using that value if present instead of the stated default.

Default Ruby versions are sticky

---

lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/prepare_app_bundler_and_ruby.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
lib/heroku_buildpack_ruby/user_comms.rb
spec/unit/ruby_detect_version_spec.rb

When someone is using the default version of Ruby let them know that we think they should be explicit about it with a warning.
This commit also introduces UserComms#close as an explicit point when warnings that have been saved for later can be emitted

Warn on default ruby usage

---

lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/cache_copy.rb
lib/heroku_buildpack_ruby/user_comms.rb
spec/cnb/buildpack_spec.rb
spec/hatchet/buildpack_spec.rb
spec/unit/cache_copy_spec.rb

This is so easy it's a joke. Use the layers dir to install gems. It's literally that easy. The bulk of the work here was to change my CNB model to allow re-deploying the same app.
The challenge with implementing this in V2 is the location of the cache is not present in run and build time. What this means is that we end up needing to copy the contents of the cache directory to the location where the gems will end up living before install, and then copy them back after the install. This was accomplished by introducing a "cache copy" object with an interface that wraps another action.

[changelog skip] Cache bundler (gems) dependencies

---

.circleci/config.yml
bin/support/bash_functions.sh
hatchet.json
hatchet.lock
spec/docker/bash_functions_spec.rb
spec/spec_helper.rb
spec/unit/bash_functions_spec.rb

The goal is to use the Node buildpack to install node and yarn binaries instead of manually installing them ourselves. This is the first step.

[ci skip] Teach the Ruby buildpack to run other buildpacks

---

lib/buildpack.rb
lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/bundle_install.rb
lib/heroku_buildpack_ruby/bundler_detect_version.rb
lib/heroku_buildpack_ruby/bundler_download.rb
lib/heroku_buildpack_ruby/bundler_lockfile_parser.rb
lib/heroku_buildpack_ruby/bundler_strip_bundled_with.rb
lib/heroku_buildpack_ruby/cache_copy.rb
lib/heroku_buildpack_ruby/curl_fetch.rb
lib/heroku_buildpack_ruby/env_proxy.rb
lib/heroku_buildpack_ruby/env_proxy/base.rb
lib/heroku_buildpack_ruby/metadata/cnb.rb
lib/heroku_buildpack_ruby/metadata/v2.rb
lib/heroku_buildpack_ruby/prepare_app_bundler_and_ruby.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
lib/heroku_buildpack_ruby/ruby_download.rb
spec/docker/bash_functions_spec.rb
spec/spec_helper.rb
spec/unit/bash_functions_spec.rb
spec/unit/bundle_install_spec.rb
spec/unit/bundler_lockfile_parser_spec.rb
spec/unit/bundler_strip_bundled_with_spec.rb
spec/unit/cache_copy_spec.rb
spec/unit/env_proxy_spec.rb
spec/unit/metadata_spec.rb
spec/unit/prepare_app_bundler_and_ruby_spec.rb

Calling Pathname.new creates a new pathname each time while calling `Pathname()` will only allocate it it's not already a pathname.
```
require 'benchmark/ips'
require 'pathname'
p = Pathname.new(".")
Benchmark.ips do |x|
x.report("Pathname.new") { Pathname.new(p) }
x.report("Pathname()  ") { Pathname(p) }
x.compare!
end
```
The resulting code is nearly ~7-8x faster. While it's likely not going to be a bottleneck anytime soon, let's not be in a habit of writing slow code when it's just as easy and clean to use faster code.

[changelog skip] Don't re-allocate Pathname

---

bin/compile
bin/support/bash_functions.sh
hatchet.json
hatchet.lock
spec/hatchet/buildpack_spec.rb
spec/unit/bash_functions_spec.rb

The existing ruby buildpack detects when an app needs a node version then we download one and put it on the path, same for yarn. This causes confusion since if someone looks up docs for node on the platform such as how to specify a node version, the docs are not valid for heroku/ruby's node version, only if you're using heroku/nodejs. 
Instead of having diverging deploy experiences this commit will allow the Ruby buildpack to download heroku/nodejs buildpack and run `bin/compile` on the app before running it's own bin/compile
```
rspec spec/hatchet/buildpack_spec.rb:23
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (16/16), 4.31 KiB | 2.15 MiB/s, done.
Total 16 …
```

[changelog skip] Install node via heroku/nodejs in V2

---

lib/heroku_buildpack_ruby/env_proxy/base.rb
spec/unit/env_proxy_spec.rb

Previously we were not ensuring that there was a newline after each exported env var:
```
$ heroku run /bin/bash -a hatchet-t-1972d0f4da
Running /bin/bash on ⬢ hatchet-t-1972d0f4da... up, 
~ $ /bin/cat .profile.d/ruby.sh
export PATH="$HOME/.heroku/ruby/bundler/bin:$HOME/.heroku/ruby/ruby/bin:$PATH"export GEM_PATH="$HOME/.heroku/ruby/gems:$HOME/.heroku/ruby/gems:$HOME/.heroku/ruby/bundler:$GEM_PATH"export BUNDLE_GEMFILE="$HOME/Gemfile"export BUNDLE_BIN="$HOME/.heroku/ruby/gems/bin"export BUNDLE_PATH="$HOME/.heroku/ruby/gems"export BUNDLE_WITHOUT="${BUNDLE_WITHOUT:-development:test}"export BUNDLE_DEPLOYMENT="1"export BUNDLE_GLOBAL_PATH_APPENDS_RUBY_SOURCE="1
```
This patch fixes that behavior and tests for it.

[changelog skip] Fix exporting path

---

lib/heroku_buildpack_ruby/bundle_install.rb
spec/hatchet/buildpack_spec.rb

Nokogiri is a HTML parser that is a native extension and needs to compile and link to libxml2.
Nokogiri ships with a version of vendor libxml2 and when you run `bundle install` with nokogiri it defaults to using the vendor version.
The stack image of Heroku provides libxml2. It's important that we tell nokogiri to use the stack image's version of libxml2 otherwise when libxml2 receives a security patch via the stack, nokogiri will not receive the patch.
To facilitate this we can set the env var NOKOGIRI_USE_SYSTEM_LIBRARIES=true. While this is tested in the existing Ruby buildpack https://github.com/heroku/heroku-buildpack-ruby/blob/38cb9c1e8e16fd09cdf2086387fe9a1882d920de/spec/hatchet/bugs_spec.rb#L4-L8 the test is not valid as it will not emit a warning even if it does not build with …

[changelog skip] Ensure that Nokogiri compiles against system

---

bin/detect
bin/support/bash_functions.sh
lib/heroku_buildpack_ruby/toml.rb
spec/cnb/buildpack_spec.rb
spec/unit/bash_functions_spec.rb

By requiring a name that we do not provide in the buildpack plan https://github.com/buildpacks/spec/blob/main/buildpack.md#build-plan-toml we're essentially telling our build system that we need node to run before Ruby.
There is a failing pack/cnb test. I believe it's failing because my copy of pack does not know about github.com/heroku/nodejs-engine-buildpack and I'm not sure how to let it know.
In addition, I'm not sure if we can provide a better debugging experience here. When this fails it looks like this:
```
RuntimeError:
Command "pack build minimal-heroku-buildpack-ruby-tests:d35c175ee32726c841bc68be474a941c --path /Users/rschneeman/Documents/projects/work/minimal-ruby/repos/ruby_apps/minimal_webpacker --builder heroku/buildpacks:18 --buildpack …
```

[changelog skip] Install node via CNB plan

---

README.md
lib/heroku_buildpack_ruby/bundler_lockfile_parser.rb
spec/unit/bundler_lockfile_parser_spec.rb

The lock file parser has reference to other bundler defined constants such as Bundle::Source. While we could attempt to whack-a-mole each of these requires, that would be brittle. Instead we can require the entirety of bundler.
The existing test did not catch this because it is being called from within a bundler context already. To write a failing test that would have caught this issue, I needed a pristine ruby environment without bundler loaded. To get this I wrote the code to text against to a script file. Then I am manually executing that script via Bash.new("ruby script.rb"). And I'm wrapping that in a Bundler.with_original_env. This combination provides a similar/same environment as the Ruby buildpack (executing the code without bundler loaded yet).
This approach caused the old code …

[changelog skip] Fix lockfile parser with test

---

lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/bash.rb
lib/heroku_buildpack_ruby/env_proxy.rb
lib/heroku_buildpack_ruby/env_proxy/base.rb
lib/heroku_buildpack_ruby/env_proxy/default.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
lib/heroku_buildpack_ruby/user_env_from_dir.rb
spec/cnb/buildpack_spec.rb
spec/hatchet/buildpack_spec.rb
spec/unit/bash_functions_spec.rb
spec/unit/bash_spec.rb
spec/unit/bundle_install_spec.rb
spec/unit/env_proxy_spec.rb
spec/unit/user_env_from_dir_spec.rb

Most other buildpacks import the user defined config values into the same process that is running the buildpack code. The Ruby buildpack gains additional control by not doing this and instead parsing and storing this information so it can be used later.
This is a multi purpose class that encapsulates env parsing logic. It acts similar to the ENV hash.
Populating this object and creating it are decoupled. This allows us to create a global instance before loading the env directory, and then later populate it.
The `UserEnv` constant is a global instance of `UserEnvFromDir`. All code can depend on it being present. It is being accessed by `Bash`, `EnvProxy::Default`, `EnvProxy::Base`, and `EnvProxy` as well as the top level HerokuBuildpackRuby methods
This class is now aware of the UserEnv …

[changelog skip] Support User Env config vars

---

bin/compile
bin/support/bash_functions.sh
hatchet.json
hatchet.lock
spec/hatchet/buildpack_spec.rb
spec/unit/bash_functions_spec.rb

The `execjs` gem allows Ruby code to execute javascript. It does this by searching for several possible implementations:
- The ruby racer (V8 distributed as a Ruby gem)
- This gems is extremely heavy, takes a long time to compile, frequently fails compilation and is generally not commonly used.
- MinRacer (A paired down interface to V8 distrbuted as a Ruby gem)
- From the readme: Unlike therubyracer, mini_racer only implements a minimal bridge. This reduces the surface area making upgrading v8 much simpler and exhaustive testing simpler.
- System installation of `node`
Prior to the introduction of `mini_racer` the most common and popular development strategy was to depend on a system version of `node`. This PR implements existing behavior in the old buildpack where we install node if …

[changelog skip] Install node for apps with execjs

---

spec/cnb/buildpack_spec.rb
spec/docker/bash_functions_spec.rb
spec/hatchet/buildpack_spec.rb
spec/unit/assets_precompile_spec.rb
spec/unit/bash_functions_spec.rb
spec/unit/bundle_install_spec.rb
spec/unit/bundler_detect_version_spec.rb
spec/unit/bundler_lockfile_parser_spec.rb
spec/unit/bundler_strip_bundled_with_spec.rb
spec/unit/cache_copy_spec.rb
spec/unit/env_proxy_spec.rb
spec/unit/metadata_spec.rb
spec/unit/prepare_app_bundler_and_ruby_spec.rb
spec/unit/rake_detect_spec.rb
spec/unit/ruby_detect_version_spec.rb
spec/unit/ruby_download_spec.rb
spec/unit/toml_spec.rb

By having all our specs in the namespace it allows us to reference constants without having to use the fully qualified `HerokuBuildpackRuby::` EVERY time.
This change wraps all spec definitions in a `module HerokuBuildpackRuby` block, adds indentation, and removes fully qualified constants in favor of their short equivalents.

[changelog skip] Wrap all specs in a namespace

---

lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/assets_precompile.rb
lib/heroku_buildpack_ruby/bundle_install.rb
lib/heroku_buildpack_ruby/rake_detect.rb
lib/heroku_buildpack_ruby/rake_task.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
lib/heroku_buildpack_ruby/ruby_download.rb
lib/heroku_buildpack_ruby/user_comms.rb
spec/spec_helper.rb
spec/unit/user_comms_spec.rb

This commit adds a different "CNB" logging style to the buildpack. Other smaller changes:
- The UserComms class is now directly tested
- UserComms#puts now UserComms#info
- UserComms#warn_now takes kwargs instead of just a single message, this allows us to consistently format links and titles across the project
- UserComms#error raises an error that can be caught later instead of exiting immediately (this can be used later for cleanup handling the error)

[changelog skip] CNB logging style

---

README.md
bin/compile
bin/detect
bin/support/bash_functions.sh
lib/heroku_buildpack_ruby/bash.rb
lib/heroku_buildpack_ruby/bundle_install.rb
lib/heroku_buildpack_ruby/curl_fetch.rb
lib/heroku_buildpack_ruby/ruby_detect_version.rb
lib/heroku_buildpack_ruby/ruby_download.rb
lib/heroku_buildpack_ruby/ruby_version_info.rb
spec/hatchet/buildpack_spec.rb
spec/spec_helper.rb
spec/unit/bash_functions_spec.rb
spec/unit/bash_spec.rb
spec/unit/bundle_install_spec.rb
spec/unit/curl_fetch_spec.rb
spec/unit/prepare_app_bundler_and_ruby_spec.rb
spec/unit/ruby_detect_version_spec.rb
spec/unit/ruby_download_spec.rb
spec/unit/ruby_version_info_spec.rb

When an app is deploying that need the JVM for JRuby we can lean on the heroku/jvm buildpack instead of managing our own java installation. This allows for separation of concerns and not having to duplicate logic.
This is similar to the v2 logic for Node.

[changelog skip] Jruby support - V2

---

.circleci/config.yml
spec/docker/bash_functions_spec.rb

The "machine" executor has a number of limitations and edge cases, not to mention that the RVM installation is very buggy and frequently causes the build to break.
This commit moves to use docker along with setting up "remote docker" https://circleci.com/docs/2.0/building-docker-images/

[close #26][changelog skip] Use docker executor on CI

---

.rspec
Gemfile.lock
README.md
bin/support/bash_functions.sh
spec/cnb/buildpack_spec.rb
spec/spec_helper.rb
spec/unit/bash_functions_spec.rb

This PR makes the "build plan" bash functions more modular by appending to the file instead of overriding it. This allows us to append on jvm without requiring a matrix of feature support.
I've added an integration test for this behavior, but eventually, we need to modify the Ruby builder so that the JVM buildpack is in the default detect order (A similar PR is done in https://github.com/heroku/pack-images/pull/132, though it is pending work described in https://github.com/heroku/heroku-buildpack-ruby-experimental/issues/27).
I'll go ahead and merge this in before the builder work is complete. That work is being tracked in an issue. https://github.com/heroku/heroku-buildpack-ruby-experimental/issues/36

[changelog skip] CNB Request JVM in Detect

---

README.md
bin/release
lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/default_process_types.rb
lib/heroku_buildpack_ruby/release_launch_info.rb
spec/cnb/buildpack_spec.rb
spec/hatchet/buildpack_spec.rb
spec/unit/default_process_types_spec.rb
spec/unit/release_launch_info_spec.rb

Currently here's how the process types are defined.
- Type: "rake"
- Not needed `heroku run rake` will execute correctly without a custom process type
- Having this here makes `heroku run rake` a special case that can be difficult to debug if there's a problem with `bundle exec"
- Type: "console"
- Ruby: "bundle exec irb"
- Rails 2: "bundle exec script/console" # Drop Rails 2 support
- Rails 3: "bundle exec rails console"
- Rails 4: "bin/rails console"
- Type: "web"
- Ruby: None
- Rack:
- Thin:    "bundle exec thin start -R config.ru -e $RACK_ENV -p ${PORT:-5000}" :
- No thin: "bundle exec rackup config.ru -p ${PORT:-5000}"
- Rails 2: # Drop Rails 2 support
- Thin:    "bundle exec thin start -e $RAILS_ENV -p ${PORT:-5000}"
- No thin: "bundle exec ruby script/server -p ${PORT:-5000}"
- …

[changelog skip] Default process types

---

Gemfile.lock
bin/build
bin/compile
bin/support/bash_functions.sh
spec/cnb/buildpack_spec.rb
spec/hatchet/buildpack_spec.rb

Previously the function `compile_buildpack_v2` directly uses `$1`, `$2`, and `$3`. This change updates this function to instead use named local variables.
- In addition, there was a typo in the output to the user.
- Update gems

[changelog skip] Use named variables instead of bash args

---

README.md
lib/heroku_buildpack_ruby.rb
lib/heroku_buildpack_ruby/metadata/cnb.rb
lib/heroku_buildpack_ruby/metadata/v2.rb
lib/heroku_buildpack_ruby/set_default_env_vars.rb
spec/cnb/buildpack_spec.rb
spec/hatchet/buildpack_spec.rb
spec/unit/set_default_env_vars_spec.rb

Previously some of these env vars were set conditionally based on library presence (such as only setting JRUBY_OPTS  if the app is using jruby). For these selected env vars, there's minimal risk in setting an env var default that is ultimately not needed. As a result all env vars are set for all Ruby applications.
Current default env vars:
- RACK_ENV
- RAILS_ENV
- JRUBY_OPTS
- DISABLE_SPRING
- SECRET_KEY_BASE
- MALLOC_ARENA_MAX
- RAILS_LOG_TO_STDOUT
- RAILS_SERVE_STATIC_FILES

[changelog skip] Set default env vars

---

spec/cnb/buildpack_spec.rb

I added a `package.json` to the example Rails app so this test now passes.
https://github.com/heroku/ruby-getting-started/pull/75#issuecomment-802256353

[changelog skip] Execute CNB test of Rails app

---

.github/dependabot.yml

See:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems
I've also:
* Changed the frequency to daily, so we don't have to wait as long.
* Removed the concurrent PRs limit (since now this repo is under the `heroku` org, the Circle CI concurrency limits are a non-issue).
* Removed the `labels` config which causes the default to be used, which (a) does the same but more (adds lang specific labels), but also auto-creates the labels, which fixed the errors seen in #49 etc.
Refs GUS-W-9678950.

Enable Dependabot for GitHub Actions [changelog skip]

---

.github/workflows/check_changelog.yml

So we don't have to add the `skip changelog` label each time, and for parity with all of our other repos.
This is identical to forcedotcom/sf-fx-runtime-nodejs#191.

Make Check Changelog skip Dependabot PRs

---

spec/spec_helper.rb

Pins the builder version until a more complete fix lands in #79, so I can merge #76.
See #79 and:
https://heroku.slack.com/archives/C01R6FJ738U/p1636658489053400?thread_ts=1636650731.042300&cid=C01R6FJ738U

Temporarily pin builder version to fix CI

---

LICENSE

Since:
- it's the license Salesforce prefers that we use for open source projects:
https://github.com/salesforce/oss-template/blob/master/license_info.md
- it's what some of our other newer repositories are already using, and it would be great to be consistent
- it's not that different from MIT:
https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/
All contributors to this repository so far are Salesforce employees, so there are no external code contributors from whom we need to ask permission before changing the license type.
GUS-W-10140085.

Switch to BSD 3-Clause License

---

buildpack.toml

This `.env` file is no longer used. It was copied over from the legacy buildpack. In addition we no longer support `cedar-14` or `heroku-16`.
GUS-W-8216066

Remove unused `.env` file

---

.circleci/config.yml
.gitignore
Gemfile.lock
bin/detect
bin/support/bash_functions.sh
build.sh
buildpack.toml
package.toml
spec/spec_helper.rb

The Ruby buildpack needs a Ruby binary to "bootstrap" its own execution. With v2 this is done at release time and when being used via git dynamically in `bin/compile`.
That same behavior was ported over to this buildpack, however the directory we write to cannot be in the same directory as the buildpack itself. This causes an error:
```
[INFO] Discovering process types
[INFO] Procfile declares types -> web
ERROR: failed to build: exit status 1
stderr: mkdir: cannot create directory '/cnb/buildpacks/heroku_ruby/0.0.1/vendor/ruby': Permission denied
ERROR: failed to build: executing lifecycle: failed with status code: 145
```
Described in buildpacks/pack#1322 the only reason builds were previously working is that another image using the Ruby identifier and the same version were previously …

Fix pack tests

---

CHANGELOG.md
README.md
buildpacks/ruby/src/user_errors.rs

- Use formatdoc! instead of format! in errors
We don't want to emit the extra whitespace here. Use `formatdoc!` macro instead of `format!` (by mistake).
This would be a hard one to catch. I wonder if there's a way to detect/warn on it somehow. Maybe with clippy and a custom rule?
- Add version to changelog and document. It's unintuitive why the first release was 2.0.0 so I added a note.

Use formatdoc! instead of format! in errors

---

README.md

Since the repository has been renamed:
https://github.com/heroku/cnb-builder-images/issues/396
GUS-W-14201543.

Update builder repo name to cnb-builder-images

---

buildpacks/ruby/src/gem_list.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/rake_task_detect.rs
buildpacks/ruby/tests/integration_test.rs
commons/src/gemfile_lock.rs

To unblock #217.
Fixed using `cargo clippy --all-targets --fix`.
`warning: matching over () is more explicit`
https://rust-lang.github.io/rust-clippy/master/index.html#ignored_unit_patterns
`warning: unnecessary hashes around raw string literal` https://rust-lang.github.io/rust-clippy/master/index.html#needless_raw_string_hashes
As seen in:
https://github.com/heroku/buildpacks-ruby/actions/runs/6456039106/job/17524710712?pr=217
GUS-W-14258338.

Fix lint errors with Rust 1.73 and 1.74

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/buildpack.toml

Adjusts the buildpack `name`, `description` and `keywords` in `buildpack.toml` to match the style discussed in:
https://github.com/heroku/cnb-builder-images/issues/408
These fields are used by the CNB registry and can also be seen in the output of `pack builder inspect`. They are not used by `pack build` or Kodon.
In addition, I've cleaned up the `[metadata]` table/subtables to match the more concise style used by the Procfile and Python CNBs.
GUS-W-14121598.

Update buildpack metadata in buildpack.toml

---

Cargo.toml
buildpacks/ruby/Cargo.toml
buildpacks/ruby/src/bin/agentmon_loop.rs
buildpacks/ruby/src/bin/launch_daemon.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/tests/integration_test.rs
commons/Cargo.toml
commons/bin/print_style_guide.rs
commons/src/cache.rs
commons/src/cache/config.rs
commons/src/cache/error.rs
commons/src/layer.rs
commons/src/lib.rs
commons/src/output/build_log.rs
commons/src/output/warn_later.rs

As of the Cargo included in Rust 1.74, lints can now be configured in `Cargo.toml` across whole crates/workspaces:
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section
https://doc.rust-lang.org/stable/cargo/reference/workspaces.html#the-lints-table
This reduces the boilerplate, and the chance that we forget to enable lints in some targets. The only thing we need to remember is to add the `[lints] workspace = true` to any new crates in the future.
Making this switch exposed a few places where lints weren't enabled and issues had been missed, which have been fixed now.
Since this feature requires Rust 1.74, the MSRV has also been bumped (however, libcnb 0.16.0 already requires Rust 1.74, so in practice this …

Switch to Cargo.toml based lint configuration

---

Cargo.toml
buildpacks/ruby/src/gem_list.rs
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/rake_status.rs
buildpacks/ruby/src/rake_task_detect.rs
buildpacks/ruby/tests/integration_test.rs
clippy.toml
commons/bin/print_style_guide.rs
commons/src/cache/clean.rs
commons/src/cache/in_app_dir_cache_layer.rs
commons/src/output/background_timer.rs
commons/src/output/util.rs

Enables some off-by-default lints that we already use in the `libcnb.rs` repository.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unreachable-pub
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code
https://rust-lang.github.io/rust-clippy/master/index.html#/panic_in_result_fn
https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used
GUS-W-14523799.

Enable additional rustc and Clippy lints

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/user_errors.rs

It's best practice to use `try_exists()` instead of `exists()` when checking if a file exists or not because if there's a problem with the file (such as a permissions issue) then the check might fail even though the file is on disk. This seems like not a big deal, but can be very confusing when telling users "we didn't do X because you are missing file Y" but when they debug they see file Y and don't realize that the real problem isn't "missing file" but it's the hidden error preventing `exists()` from returning a true.
This commit uses fs_err_try_exists() from fs-err library that was introduced in: https://github.com/andrewhickman/fs-err/pull/48.
There are a few other places where `exists` is still called, those are nested in areas that don't already return a Result so they're harder to …

Report io error when detect cannot read a file.

---

Cargo.lock
Cargo.toml
buildpacks/ruby/Cargo.toml
commons/Cargo.toml

As of Cargo 1.75 the `version` property in `Cargo.toml` is now optional, and if omitted is the same as having specified `version = "0.0.0"` and `publish = false`:
https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
Therefore for crates that we do not publish, we can now remove both the `version` and `publish` properties, avoiding the need for the fake `0.0.0` version that differs from the actual buildpack version in `buildpack.toml`.
GUS-W-14821120.

Simplify Cargo metadata for `publish = false` crates

---

.github/workflows/ci.yml

As of Pack 0.33.0 (which this repo is using thanks to #462), there is a new `--force-color` argument that makes `pack build` output logs in colour even if a TTY wasn't detected (as is the case on GHA):
https://github.com/buildpacks/pack/releases/tag/v0.33.0
This makes the `script -e -c` TTY workaround unnecessary. (It's also not needed for any direct Cargo usages, since they are covered by the existing `CARGO_TERM_COLOR: always`.)
I've also:
- removed a redundant `cargo build` step (run does a build, and the Cargo compilation output can be suppressed using `--quiet`)
- replaced a manual git clone with `actions/checkout`, since it handles things like retries, faster shallow clones etc.
GUS-W-14968745.

Use `pack build --force-color` in CI instead of `script` TTY workaround

---

commons/src/output/warn_later.rs

CI started failing when a new rust was released with new clippy suggestions. This is failing on main:
```
error: initializer for `thread_local` value can be made `const`
--> commons/src/output/warn_later.rs:11:65
|
11 | thread_local!(static WARN_LATER: RefCell<Option<Vec<String>>> = RefCell::new(None));
|                                                                 ^^^^^^^^^^^^^^^^^^ help: replace with: `const { RefCell::new(None) }`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#thread_local_initializer_can_be_made_const
= note: `-D clippy::thread-local-initializer-can-be-made-const` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::thread_local_initializer_can_be_made_const)]`
error: could not compile …
```

Apply clippy suggestion

---

Cargo.lock
buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/Cargo.toml
buildpacks/ruby/buildpack.toml
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/target_id.rs
buildpacks/ruby/tests/integration_test.rs
commons/Cargo.toml
commons/src/cache/in_app_dir_cache_layer.rs
commons/src/layer/configure_env_layer.rs
commons/src/metadata_digest.rs
docs/application_contract.md

Buildpack API 0.10 removed the concept of stacks in favor of targets https://github.com/heroku/libcnb.rs/pull/773.
This commit works to upgrade applications in place by migrating metadata to support the new serialization format. This is supported by implementing TryMigrate from the `magic_migrate` crate https://docs.rs/magic_migrate/latest/magic_migrate/macro.try_migrate_link.html.
https://www.youtube.com/watch?v=NnP5iDKwuwk
- Reference PR from Python: https://github.com/heroku/buildpacks-python/pull/197
Notably, this does NOT introduce support for `heroku-24` and multiple architectures. That work will come after upgrading from stacks to targets.

Switch from stacks to targets AKA "Stay on target"

---

Cargo.lock
buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/buildpack.toml
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/target_id.rs
buildpacks/ruby/tests/integration_test.rs

Heroku 24 stack image supports both arm64 and amd64. The Ruby binaries are available on heroku-24 compiled to these two stacks https://github.com/heroku/docker-heroku-ruby-builder/pull/38. The buildpack adds support by:
- Updating the `buildpackl.toml` to include ARM architecture
- Using architecture information to build the URL for Ubuntu 24.04 (heroku-24)
- Integration testing on all supported Ubuntu versions

Support Heroku-24 and ARM architecture

---

.github/workflows/ci.yml

Heroku 24 is now a trusted and suggested builder in [pack](https://github.com/buildpacks/pack/pull/2178). However, now running pack build with heroku-22 now fails due to a bug that suggests the builder is not trusted even though it is configured to be. 
```
Run pack build my-image --force-color --builder heroku/builder:22 --buildpack heroku/nodejs-engine --buildpack packaged/x86_64-unknown-linux-musl/debug/heroku_ruby --path tmp/ruby-getting-started --pull-policy never 
ERROR: failed to build: fetching lifecycle image: image buildpacksio/lifecycle:0.19.6 does not exist on the daemon: not found
``` 
We can update the version of the heroku builder that the github workflow for printing getting started is using in order for this action to pass.

update builder to heroku-24 on print getting started guide github action

---

.github/workflows/ci.yml

Previously, all Heroku runners used AMD (x86) CPU architecture. We added the ability to build and run on an ARM machine (aarch64, like an M3 Mac), but building binaries for ARM required a beta GitHub Action (GHA) runner. The GHA runner beta required extra invocations to setup tools on the machine (such as installing docker). 
The GHA ARM runners are now out of beta. This PR adds a test that exercises the ARM codepath on CI in addition to the existing AMD codepath.
GUS-W-15805220

Test getting started guide with ARM && AMD

---

.github/workflows/check_changelog.yml
.github/workflows/ci.yml

To update to Ubuntu 24.04, and to prevent the rate limit issues mentioned here:
https://github.com/heroku/buildpacks-go/pull/283
I've not added the run image pre-pulling step used by some of the other CNB repos, since this repo doesn't currently use a matrix to test builder image versions, and instead varies the builder test by test, which (a) means I'd have to hardcode a list, (b) means that the benefit would be less.
See also:
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZR57becb9df8d94f80b132168fd
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
GUS-W-16238120.

Switch to the new GitHub Actions runner groups

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/steps/get_default_process.rs

When using `docker run`, the default rails app configuration assumes the existence of a `$PORT` environmental variable but does not tell the user that it is required. By making the lack of a definition for the environmental variable, the user can understand how to run the application properly.
Resolves #306

Configure process to complain about unset variable

---

buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/steps/default_env.rs
commons/src/cache/app_cache.rs
commons/src/cache/app_cache_collection.rs
commons/src/cache/in_app_dir_cache_layer.rs
commons/src/layer/configure_env_layer.rs

This mostly allows using the deprecated API while we transition to the new API. This would allow us to merge #321 as a smaller PR and then we can gradually transition the rest of the codebase instead of one large shebang re-write.

[Stacked] Fixes CI linting

---

Cargo.lock
buildpacks/ruby/Cargo.toml
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/steps/default_env.rs
buildpacks/ruby/tests/integration_test.rs
commons/Cargo.toml
commons/src/cache/app_cache.rs
commons/src/cache/app_cache_collection.rs
commons/src/cache/in_app_dir_cache_layer.rs
commons/src/layer/configure_env_layer.rs

Migrate metrics agent layer to Struct API and bullet Stream. Taking over from #320 with a smaller and more modular process.

Migrate metrics agent layer to Struct API and bullet Stream

---

buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs

Commits should be stand-alone.

Update Ruby Install Layer to Struct API and bullet stream output

---

buildpacks/ruby/src/layers.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/layers/shared.rs
buildpacks/ruby/src/main.rs

PR #326 pointed out inconsistencies in the style of output for different layers and asked for additional tests. This refactor makes that request easier by introducing shared logic for invalid metadata and cache invalidation.
It's a ducktyping approach based on two traits:
- `magic_migrate::TryMigrate` provides an interface to (possibly) migrate invalid metadata or display errors
- `MetadataDiff` provides an interface to allow standardize cache invalidation and restoration logic
These allow me to remove the bulk of cache invalidation logic into a central shared location. They also expose a clean interface for unit testing cache invalidation logic, which can then be used on other layers.
I described some of the background desires in #325, comment: …

Shared layer logic for consistent output and unit testing

---

Cargo.lock
commons/Cargo.toml
commons/src/cache/app_cache.rs
commons/src/cache/clean.rs
commons/src/cache/config.rs

Byte unit 4 broke a lot of interfaces that we depended on. This commit uses the new interfaces:
- Byte::from_bytes -> Byte::from_<type> (like Byte::from_u64)
- Byte.get_appropriate_unit(bool) -> Byte.get_appropriate_unit(UnitType)
- macros such as `n_mib_bytes` are no longer present.
This has one (technically) breaking change in the `mib` convenience function provided by commons. However if a literal is being used in the code (which it is in the Ruby main.rs) then it is not affected.
Even though lots of things changed internally, the overall interface to AppCache stayed (almost) stable and no code inside of the main buildpack needed to be updated. That indicates a relatively successful encapsulation attempt.
Moving forward it would be best to not directly rely on types from external …

Update byte-unit dependency with breaking changes

---

buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/shared.rs
buildpacks/ruby/src/main.rs

Details in commits. The handle layer caching logic is exactly the same as the Ruby install layer https://github.com/heroku/buildpacks-ruby/blob/ec57995644a5feb3a89558918551373dc8d3541b/buildpacks/ruby/src/layers/ruby_install_layer.rs#L40-L58

Move bundle download to struct API and bullet stream

---

commons/CHANGELOG.md
commons/Cargo.toml
commons/src/cache/app_cache.rs
commons/src/cache/error.rs

Each commit compiles and is intended to be small and readable. More information on why this option was chosen is in https://github.com/heroku/buildpacks-ruby/issues/302#issuecomment-2419661964

Close #302 Copy Mtimes in the AppCache

---

buildpacks/ruby/src/steps/default_env.rs

The trait based API provided by DefaultEnvLayer is now deprecated. This PR switches to the newer struct based API.

Use struct API when setting default envs

---

buildpacks/ruby/src/layers/shared.rs
buildpacks/ruby/src/main.rs
commons/src/gemfile_lock.rs
commons/src/metadata_digest.rs

- Addresses #272 (Deny unknown fields)

Deny unknown fields

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/steps/get_default_process.rs
buildpacks/ruby/tests/fixtures/default_ruby/Gemfile
buildpacks/ruby/tests/fixtures/default_ruby/Gemfile.lock
buildpacks/ruby/tests/integration_test.rs
docs/application_contract.md

IPv6 is the future. Here's some more context heroku/roadmap#40.
Related https://github.com/heroku/ruby-getting-started/pull/165

Change default process type host to IPv6 `::`

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/shared.rs

There was a bug reported where deploying a Ruby application after modifying the Gemfile.lock would result in an error because we were skipping running `bundle install`. Debugging this lead me to find that we were returning the incorrect value from our shared cache logic (accidentally returning the currnt/now value rather than the old value).
The idea behind `cached_layer_write_metadata` is to either return the old cached data or return a message stating why it couldn't be returned. It was accidentally returning the new/current value instead. This feature is used in most (nearly all) of the layers, like https://github.com/heroku/buildpacks-ruby/blob/a3f5834fb0013c6b583016c05e3b93fda62504f2/buildpacks/ruby/src/layers/bundle_install_layer.rs#L56-L62. In this logic there are some values in …

Fix shared layer logic

---

Cargo.lock
Cargo.toml
buildpacks/ruby/Cargo.toml
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/layers/shared.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/target_id.rs
buildpacks/ruby/tests/integration_test.rs

The `MetadataDiff` was a prototype for how to extract cache clearing logic to a centralized trait. From there I changed the name and built a proc-macro that can generate the same logic https://github.com/heroku-buildpacks/cache_diff. The benefit of the proc macro is it works with defaults out of the box and adds consistency. 
This PR moves the old code using MetadataDiff to now use `CacheDiff`. In the process I refactored some logic, namely how the OS distribution information is stored as metadata. Commits are small, sequential and self described.

Adopt CacheDiff (crate) over MetadataDiff (internal)

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs

These were added as a part of the RubyConf hackweek, but I just merged that PR in. Between then and now, I added metadata that didn't include the container attribute.
The attribute is described here: https://serde.rs/container-attrs.html.
> Always error during deserialization when encountering unknown fields. When this attribute is not present, by default unknown fields are ignored for self-describing formats like JSON.
>
> Note: this attribute is not supported in combination with [flatten](https://serde.rs/field-attrs.html#flatten), neither on the outer struct nor on the flattened field.
I proposed adding it to all structs here https://github.com/heroku/buildpacks/discussions/23

Add missing deny unknown fields

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/main.rs
buildpacks/ruby/tests/integration_test.rs

Rails 8.0.1 needs Ruby 3.2+ and unfortunately they decided to stop shipping with a Ruby version in the Gemfile. I don't yet have `.ruby-version` support, but this will at least allow a `rails new` app to work on Heroku with the default versions.

Update default bundler and ruby versions

---

Cargo.lock
Cargo.toml
buildpacks/ruby/Cargo.toml
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
commons/Cargo.toml
commons/src/layer/diff_migrate.rs
commons/src/layer/fixtures/metadata_migration_example.md

Commits are relatively self contained and in order.

Upgrade to magic_migrate proc macro interface

---

Cargo.lock
Cargo.toml
buildpacks/ruby/Cargo.toml
buildpacks/ruby/src/gem_list.rs
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/rake_task_detect.rs
buildpacks/ruby/src/steps/rake_assets_install.rs
buildpacks/ruby/src/user_errors.rs
commons/Cargo.toml

To reduce accidentally diverging from the command formatting use use bullet stream's built in `stream_cmd` and `time_cmd` for consistent output. These come with the ability to rename a command to add extra info (like env vars).

Use bullet stream's built in `stream_cmd` and `time_cmd` for consistent output

---

buildpacks/ruby/src/gem_list.rs
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/rake_task_detect.rs
buildpacks/ruby/src/steps/detect_rake_tasks.rs
buildpacks/ruby/src/steps/get_default_process.rs
buildpacks/ruby/src/steps/rake_assets_install.rs
buildpacks/ruby/src/user_errors.rs
buildpacks/ruby/tests/integration_test.rs
commons/src/layer/fixtures/metadata_migration_example.md

Switches from stdout to the global writer which defaults to stderr. This swich guarantees consistent print output when the print stream is dropped and then we have to construct a new one to emit an error message.

Use global print output

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/tests/integration_test.rs
docs/application_contract.md

The previous logic used the `BUNDLE_PATH` environment variable to direct bundler where to install gems. This had the side effect of adding additional paths to the directory structure, so the files wouldn't be in `<layer-path>` they would be in a `<layer-path>/ruby/<major>.<minor>.0/` directory such as `<layer-path>/ruby/3.4.0`. The classic buildpack handles this by shelling out to Ruby https://github.com/heroku/heroku-buildpack-ruby/blob/b3ccc41885135ae495c604a512b523c81241914d/lib/language_pack/ruby.rb#L157. This change diverges and takes an alternative approach, using the `GEM_HOME` and `GEM_PATH` environment variables to configure installation location rather than configuring bundler directly.
When `bundle install` is run, it will install into the first `GEM_PATH` (there can be …

Configure gem install location via GEM_*

---

.github/workflows/ci.yml
Cargo.toml
buildpacks/ruby/src/main.rs
commons/src/lib.rs

Related:
- https://github.com/heroku/buildpacks-jvm/pull/766
- https://github.com/heroku/buildpacks-go/pull/349
GUS-W-18109363

Add cargo-llvm-cov test coverage reports in CI

---

Cargo.lock
buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/gem_list.rs
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/metrics_agent_install.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/rake_task_detect.rs
buildpacks/ruby/src/steps/detect_rake_tasks.rs
buildpacks/ruby/src/steps/get_default_process.rs
buildpacks/ruby/src/steps/rake_assets_install.rs
buildpacks/ruby/src/user_errors.rs
commons/src/layer/fixtures/metadata_migration_example.md

The `bullet_stream` global function interface was introduced in 0.4.0 https://github.com/heroku-buildpacks/bullet_stream/blob/ce8fd41c8886a8f0e2c5992f2bfa673838ad509a/CHANGELOG.md#v040---20250121 
This PR updates the Ruby buildpack to use the new style of printing interface over the heavier type-state interface.
A little history on why it took so long to introduce and adopt a function interface in a functional language:
The original design of the printing interface was a little bit functional with a light type-state pattern. You can see the original interface here https://github.com/heroku/buildpacks-ruby/pull/155. 
Over many pairing sessions, the type-state design was emphasized and functional style interfaces de-emphasized. It's a good pattern, but in hind-site not a good fit for the …

Switch to the bullet_stream function interface (instead of type-state "streaming" interface)

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/target_id.rs
buildpacks/ruby/tests/integration_test.rs

Since Heroku-20 is has reached end-of-life:
https://devcenter.heroku.com/changelog-items/3230
(When this is released, I'll edit the cnb-builder-images PR by hand so it only updates the newer builders, until such time as more CNBs drop support, then we can adjust the builders list used by the release automation to no longer update the manifest for heroku/builder:20)
- Removed:

Remove heroku-20 support

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/bundle_download_layer.rs
buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/src/layers/ruby_install_layer.rs
buildpacks/ruby/src/main.rs
buildpacks/ruby/src/target_id.rs
buildpacks/ruby/src/user_errors.rs
buildpacks/ruby/tests/integration_test.rs
commons/CHANGELOG.md
commons/src/cache/app_cache.rs
commons/src/metadata_digest.rs
docs/application_contract.md

Previously: We inspected the state of the last `Gemfile.lock` and user environment variables to only run `bundle install` when something changed. This provides minimal value in practice and requires a lot of plumbing. Now we call `bundle install` on every push. This adds a (relatively) negligible overhead (0.3~1s) per deploy for a fully cached app, and allows us to remove a lot of code.
- Deprecates `MetadataDigest` that was introduced to support this feature
- Removes old Metadata structs introduced before Fir went GA (details in commits)
- Removes logic used to support old metadata
Changes are structured in ordered commits with explanatory messages
GUS-W-18540827

Run `bundle install` on every push

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/layers/bundle_install_layer.rs
docs/application_contract.md

Comparing output sizes between Classic and CNB showed that the CNB produces a larger disk size:
```
Classsic: 72M    vendor/bundle/ruby/3.2.0/gems
CNB:      100M    /layers/heroku_ruby/gems
```
Investigation showed this is due to the cache dir:
```
heroku@25c680a44a16:/workspace$ du -hs /layers/heroku_ruby/gems/* | sort -h -r
70M    /layers/heroku_ruby/gems/gems                # + 2M
17M    /layers/heroku_ruby/gems/extensions          # + 5M
13M    /layers/heroku_ruby/gems/cache               # + 13M
```
This is not present in the Classic buildpack as it's being manually removed https://github.com/heroku/heroku-buildpack-ruby/blob/471f5185cca999668fcc697120754ea9e03c9119/lib/language_pack/ruby.rb#L704-L705. We can perform the same optimization by deleting this directory.
Before (568K …

Delete Rubygems cache directory

---

buildpacks/ruby/CHANGELOG.md
buildpacks/ruby/src/main.rs
buildpacks/ruby/tests/integration_test.rs

The Node.js CNB is often used by the Ruby CNB to handle asset compilation for Rails apps. A recent change to the Node.js CNB made it so that dev dependencies are pruned at the end of its build phase, but these dev dependencies are then needed when the Ruby CNB wants to do asset compilation.
To support this use case, the Node.js CNB exposes a buildplan configuration that can control how some of these features work. This PR includes that required buildplan whenever Node.js tooling is required + modifies an integration test to verify that the configuration is working.
Closes https://github.com/heroku/buildpacks-nodejs/issues/1141

Configure Node CNB to skip pruning

---

buildpacks/ruby/src/layers/bundle_install_layer.rs
buildpacks/ruby/tests/integration_test.rs
commons/src/layer/fixtures/metadata_migration_example.md

```
error: item in documentation is missing backticks
--> commons/src/layer/fixtures/metadata_migration_example.md:1:11
|
1 |  ## Setup DiffMigrateLayer for new layer Metadata
|           ^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
= note: `-D clippy::doc-markdown` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::doc_markdown)]`
help: try
|
1 -  ## Setup DiffMigrateLayer for new layer Metadata
1 +  ## Setup `DiffMigrateLayer` for new layer Metadata
|
Checking libcnb-test v0.29.0
error: item in documentation is missing backticks
--> commons/src/layer/fixtures/metadata_migration_example.md:108:13
|
108 |   - Takes a bullet_stream printer for maximal printing consistency
| …
```

Fix clippy for Rust 1.89
